### ISSUE TITLE
BUG: wrong attributes are being generated for Time and Duration in ROS1

### ISSUE THREAD

**Issue by CodeFinder2** [Greenroom-Robotics/ros-typescript-generator#10]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
You can see [here](https://github.com/Greenroom-Robotics/ros-typescript-generator/blob/master/src/lib/primitives.ts#L22) and in the following line that `sec` and `nanosec` are being generated. This is correct for [ROS2](https://docs.ros2.org/foxy/api/builtin_interfaces/msg/Time.html) but not for ROS1 where it is named `secs` and `nsecs`. Can you provide a fix for this please?

Tested with latest version. Thank you!

**Comment by MrBlenny** [comment]
Included in [1.6.4](https://github.com/Greenroom-Robotics/ros-typescript-generator/commit/e8d0406c8c33de224c55e7e067c25a8357a50cde) Thanks again @PhilippeMorier

**Comment by PhilippeMorier** [comment]
Thanks a lot for the fast release :rocket:!
