### ISSUE TITLE
How to use this on a device that doesn't have ROS

### ISSUE THREAD

**Issue by Pandananana** [Greenroom-Robotics/ros-typescript-generator#23]
- **I'm submitting a ...**
question about how to use this project

- **Summary**
I am developing a web interface to control my ROS1 robot. My machine doesn't have ROS, it connects using rosbridge. Is it still possible to use this generator, what should the path be?

- **Other information** 
No

**Comment by MrBlenny** [comment]
You would need to generate the types on a device that had access to the ROS .msg files. This could be on the robot itself, your computer or in CI if you are able to install the robots .msg / .srv files. You could then build the typescript interfaces in a library and publish them as an NPM package to use in your project.
