### ISSUE TITLE
Do you have plan to support *.srv?

### ISSUE THREAD

**Issue by hayoung0Lee** [Greenroom-Robotics/ros-typescript-generator#4]
- **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  -  [ ] question about the decisions made in the repository
  - [x] question about how to use this project

- **Summary**
Hi, thank you for your hard work! I have a question after using your project! 
  * Are you going to support generating types for `*.srv` files in the future? 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by MrBlenny** [comment]
Yes! Srv files should work already. I'll add an example.

**Comment by MrBlenny** [comment]
You'll see a heap of types ending with `Request` and `Response`. eg) https://github.com/Greenroom-Robotics/ros-typescript-generator/blob/master/examples/real-ros2/generated/msgs.ts#L13
These are generated from .srv files.

**Comment by hayoung0Lee** [comment]
> You'll see a heap of types ending with `Request` and `Response`. eg) https://github.com/Greenroom-Robotics/ros-typescript-generator/blob/master/examples/real-ros2/generated/msgs.ts#L13 These are generated from .srv files.

Wow!! Great! Thanks!

**Comment by hayoung0Lee** [comment]
> You'll see a heap of types ending with `Request` and `Response`. eg) https://github.com/Greenroom-Robotics/ros-typescript-generator/blob/master/examples/real-ros2/generated/msgs.ts#L13 These are generated from .srv files.

I have a further question. 
Types are not generated from `*.srv` when it doesn't have matching `request` and `response` file. 

- https://github.com/Greenroom-Robotics/ros-typescript-generator/tree/master/examples/basic/ros_msgs/diagnostic_msgs/srv
![image](https://user-images.githubusercontent.com/70381940/170900908-dab355a2-b94e-41dd-a6b7-fa06bb3ab10c.png)

Did you manually create `*_Request.msg` and `*_Response.msg` files from `*.srv` files?

**Comment by CodeFinder2** [comment]
@MrBlenny I would be interested in what @hayoung0Lee has asked as well. Should it work out of the box without these files and if yes, how?

I was only able to get it working by generating `*_Request.msg` and `*_Response.msg`. Is there a better way to do it?

Thanks!

**Comment by MrBlenny** [comment]
Yes sorry, I have always been running a `colcon build` which would generate the `_Request` and `_Response` files. A fix for this has been added as part of version 1.7.0
